"""replace status with enabled and test_passed

Revision ID: 85a636c209d2
Revises: b072b11d825f
Create Date: 2025-11-26 10:27:29.393694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a636c209d2'
down_revision: Union[str, Sequence[str], None] = 'b072b11d825f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tools', sa.Column('test_passed', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('tools', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('tools', 'test_passed')
    op.drop_column('tools', 'enabled')
    # ### end Alembic commands ###
