"""create visits table

Revision ID: a9fbf718e9f3
Revises: 412ff87d3456
Create Date: 2026-03-24 16:27:16.288590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9fbf718e9f3'
down_revision: Union[str, Sequence[str], None] = '412ff87d3456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.String(length=20), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('intake', 'triaged', 'auto_routed', 'pending_review', 'routed', 'in_department', 'completed', name='visitstatus'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('routing_suggestion', sa.JSON(), nullable=True),
    sa.Column('routing_decision', sa.JSON(), nullable=True),
    sa.Column('chief_complaint', sa.String(length=500), nullable=True),
    sa.Column('intake_notes', sa.Text(), nullable=True),
    sa.Column('intake_session_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['intake_session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_visits_created_at', 'visits', ['created_at'], unique=False)
    op.create_index(op.f('ix_visits_patient_id'), 'visits', ['patient_id'], unique=False)
    op.create_index('ix_visits_status', 'visits', ['status'], unique=False)
    op.create_index(op.f('ix_visits_visit_id'), 'visits', ['visit_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_visit_id'), table_name='visits')
    op.drop_index('ix_visits_status', table_name='visits')
    op.drop_index(op.f('ix_visits_patient_id'), table_name='visits')
    op.drop_index('ix_visits_created_at', table_name='visits')
    op.drop_table('visits')
    # ### end Alembic commands ###
