"""add status to tools

Revision ID: b072b11d825f
Revises: 251125_health_summary
Create Date: 2025-11-26 10:11:33.942897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b072b11d825f'
down_revision: Union[str, Sequence[str], None] = '251125_health_summary'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('api_request_example', sa.Text(), nullable=True))
    op.add_column('tools', sa.Column('api_response_example', sa.Text(), nullable=True))
    op.add_column('tools', sa.Column('status', sa.String(length=20), server_default='draft', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'status')
    op.drop_column('tools', 'api_response_example')
    op.drop_column('tools', 'api_request_example')
    # ### end Alembic commands ###
