"""extend_visit_id_to_varchar50

Revision ID: d56820a667f0
Revises: b2c3d4e5f6a7
Create Date: 2026-04-08 11:08:51.433292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd56820a667f0'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_tools_skill_id'), table_name='skill_tools')
    op.drop_table('skill_tools')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_orders_patient_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_visit_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_column('chat_sessions', 'agent_role')
    op.drop_constraint(op.f('rooms_room_number_key'), 'rooms', type_='unique')
    op.drop_index(op.f('uq_rooms_current_visit_id'), table_name='rooms')
    op.create_unique_constraint(None, 'rooms', ['current_visit_id'])
    op.alter_column('visit_steps', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('visit_steps', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('visits', 'visit_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visits', 'visit_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('visit_steps', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('visit_steps', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_constraint(None, 'rooms', type_='unique')
    op.create_index(op.f('uq_rooms_current_visit_id'), 'rooms', ['current_visit_id'], unique=True)
    op.create_unique_constraint(op.f('rooms_room_number_key'), 'rooms', ['room_number'], postgresql_nulls_not_distinct=False)
    op.add_column('chat_sessions', sa.Column('agent_role', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('visit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_type', postgresql.ENUM('lab', 'imaging', name='ordertype'), autoincrement=False, nullable=False),
    sa.Column('order_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'in_progress', 'completed', 'cancelled', name='orderstatus'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ordered_by', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('result_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fulfilled_by', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('orders_patient_id_fkey')),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], name=op.f('orders_visit_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey'))
    )
    op.create_index(op.f('ix_orders_visit_id'), 'orders', ['visit_id'], unique=False)
    op.create_index(op.f('ix_orders_patient_id'), 'orders', ['patient_id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('skills_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('when_to_use', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('when_not_to_use', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('keywords', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('examples', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('source_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('source_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_system', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_loaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('file_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='skills_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('skill_tools',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('implementation_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('parameters_schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('skill_tools_skill_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('skill_tools_pkey'))
    )
    op.create_index(op.f('ix_skill_tools_skill_id'), 'skill_tools', ['skill_id'], unique=False)
    # ### end Alembic commands ###
