"""add_message_status_and_background_task_support

Revision ID: e8bd8fafd784
Revises: 
Create Date: 2025-11-25 20:36:43.439869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8bd8fafd784'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add status column as nullable first
    op.add_column('chat_messages', sa.Column('status', sa.String(length=20), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE chat_messages SET status = 'completed' WHERE status IS NULL")
    # Now make it NOT NULL
    op.alter_column('chat_messages', 'status', nullable=False)

    op.add_column('chat_messages', sa.Column('task_id', sa.String(length=100), nullable=True))
    op.add_column('chat_messages', sa.Column('logs', sa.Text(), nullable=True))
    op.add_column('chat_messages', sa.Column('streaming_started_at', sa.DateTime(), nullable=True))
    op.add_column('chat_messages', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('chat_messages', sa.Column('error_message', sa.Text(), nullable=True))

    # Add last_updated_at as nullable first
    op.add_column('chat_messages', sa.Column('last_updated_at', sa.DateTime(), nullable=True))
    # Set default value for existing rows (use created_at as fallback)
    op.execute("UPDATE chat_messages SET last_updated_at = created_at WHERE last_updated_at IS NULL")
    # Now make it NOT NULL
    op.alter_column('chat_messages', 'last_updated_at', nullable=False)
    op.drop_column('sub_agents', 'is_core')
    op.alter_column('tools', 'tool_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'function'::character varying"))
    op.alter_column('tools', 'scope',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'global'::character varying"))
    op.drop_constraint(op.f('tools_assigned_agent_id_fkey'), 'tools', type_='foreignkey')
    op.create_foreign_key(None, 'tools', 'sub_agents', ['assigned_agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tools', type_='foreignkey')
    op.create_foreign_key(op.f('tools_assigned_agent_id_fkey'), 'tools', 'sub_agents', ['assigned_agent_id'], ['id'], ondelete='SET NULL')
    op.alter_column('tools', 'scope',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'global'::character varying"))
    op.alter_column('tools', 'tool_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'function'::character varying"))
    op.add_column('sub_agents', sa.Column('is_core', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_column('chat_messages', 'last_updated_at')
    op.drop_column('chat_messages', 'error_message')
    op.drop_column('chat_messages', 'completed_at')
    op.drop_column('chat_messages', 'streaming_started_at')
    op.drop_column('chat_messages', 'logs')
    op.drop_column('chat_messages', 'task_id')
    op.drop_column('chat_messages', 'status')
    # ### end Alembic commands ###
